print("How old are you?", end=' ')
age = input()
print("How tall are you?", end=' ')
height = input()
print("How much do you weigh?", end=' ')
weight = input()
hand = input("Are you right or left handed? ")
print(f"So, you're {age} old, {hand} handed, {height} tall and {weight} heavy.")
